name: run

on:
  workflow_call:
    inputs:
      year:
        description: "Year to process"
        required: true
        
jobs:
  check:
    name: Check
    steps:
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.34"

      - name: Install dependencies
        run: |
          sudo apt-get install bc -y
          sudo apt-get install libperl-critic-perl -y
          sudo apt-get install pylint isort black -y
          npm install -g eslint prettier

      - name: Check
        env:
          YEAR: ${{ inputs.year }}
        run: lib/main.sh check-year $YEAR

  run:
    name: Run
    steps:
      - uses: actions/checkout@v4

      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.34"
      
      - name: Run
        env:
          YEAR: ${{ inputs.year }}
        run: lib/main.sh run-year $YEAR
