name: 2015

on:
  push:
    paths:
      - 'lib/**'
      - '2015/**'
      - '.github/run-year/**'
      - '.github/workflows/2015.yaml'

jobs:
  run-2015:
    - uses: ./.github/workflows/run.yaml
      with:
        year: 2015
        
