name: 2015

on:
  push:
    paths:
      - 'lib/**'
      - '2015/**'
      - '.github/workflows/2015.yaml'

jobs:
  run-2015:
    - uses: actions/checkout@v4
    - uses: ./.github/workflows/_run-year.yml
      with:
        year: "2015"
