name: "2015"

on: 
 push:
  paths:
    - "2015/**"
    - "lib/**"
    - ".github/workflows/run.yaml"
    - ".github/workflows/2015.yaml"
 
jobs:
  y2015:
    uses: ./.github/workflows/run.yaml
    with:
      year: "2015"
