name: 2015

on:
  push:
    paths:
      - 'lib/**'
      - '2015/**'
      - '.github/workflows/2015.yaml'

jobs:
  run-2015:
    name: 2015
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/run-year
        with:
          year: "2015"
