name: "2016"

on: 
 push:
  paths:
    - "2016/**"
    - "lib/**"
    - ".github/workflows/run.yaml"
    - ".github/workflows/2016.yaml"
  branches:
    - main

jobs:
  ci:
    uses: ./.github/workflows/run.yaml
    with:
      year: "2016"
    secrets: inherit
