name: "2017"

on: 
 push:
  paths:
    - "2017/**"
    - "lib/**"
    - ".github/workflows/run.yaml"
    - ".github/workflows/2017.yaml"
  branches:
    - main

jobs:
  ci:
    uses: ./.github/workflows/run.yaml
    with:
      year: "2017"
    secrets: inherit
