name: "2018"

on: 
 push:
  paths:
    - "2018/**"
    - "lib/**"
    - ".github/workflows/run.yaml"
    - ".github/workflows/2018.yaml"
 
jobs:
  ci:
    uses: ./.github/workflows/run.yaml
    with:
      year: "2018"
