name: "2020"

on: 
 push:
  paths:
    - "2020/**"
    - "lib/**"
    - ".github/workflows/run.yaml"
    - ".github/workflows/2020.yaml"
 
jobs:
  y2020:
    uses: ./.github/workflows/run.yaml
    with:
      year: "2020"
