name: "2023"

on: 
 push:
  paths:
    - "2023/**"
    - "lib/**"
    - ".github/workflows/run.yaml"
    - ".github/workflows/2023.yaml"
  branches:
    - main

jobs:
  ci:
    uses: ./.github/workflows/run.yaml
    with:
      year: "2023"
    secrets: inherit
