name: "2024"

on:
  push:
    paths:
      - "2024/**"
      - "lib/**"
      - ".github/workflows/run.yaml"
      - ".github/workflows/2024.yaml"
    branches:
      - main
  pull_request:
    paths:
      - "2024/**"
      - "lib/**"
      - ".github/workflows/run.yaml"
      - ".github/workflows/2024.yaml"
    branches:
      - main

jobs:
  ci:
    uses: ./.github/workflows/run.yaml
    with:
      year: "2024"
    secrets: inherit
