name: on push

on:
  push:
    branches:
      - main

env:
  PYTHON_VERSION: 3.9

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: make install

      - name: Lint
        run: make lint

      - name: Tests
        run: make test-all
