name: on push

on:
  push:
    branches:
      - main
      - refactor/tests

env:
  PYTHON_VERSION: 3.9

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: make install

      - name: Lint
        run: make lint

      - name: Tests
        run: |
          for year in $(seq -w 2015 2023); do
            for day in $(seq -w 1 25); do
              if [ -d "$year/day$day" ]; then
                echo "----------------------------------------------------------------------"
                echo -e "\033[0;32mRunning tests for $year day $day ..."
                make test year=$year day=$day
              fi
            done
          done
