name: on push

on:
  push:
    branches:
      - main
      - refactor/tests

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Tests
        working-directory: src
        run: pytest -v
