name: on push

on:
  push:
    branches:
      - main

env:
  PYTHON_VERSION: 3.9

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        working-directory: ./src
        run: pip install -r requirements.txt -r requirements_dev.txt

      - name: Lint
        working-directory: ./src
        run: |
          isort --check-only .
          black --check .

      - name: Tests
        working-directory: ./src
        run: |
          for year in $(seq -w 2015 2023); do
            for day in $(seq -w 1 25); do
              if [ -d "$year/day$day" ]; then
                echo "----------------------------------------------------------------------"
                echo -e "\033[0;32mRunning tests for $year day $day ..."
                pytest -v --no-header $year/day$day
              fi
            done
          done
