name: online-tests

on:
  push:
    branches:
      - chore/no-input-no-readme

env:
  PYTHON_VERSION: 3.9

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: make install

      - name: Tests 2015 1
        run: python run.py 2015 1

      - name: Tests 2019 7
        run: python run.py 2019 7
