name: run

on:
  push:

env:
  PYTHON_VERSION: "3.9"
  NODE_VERSION: "20.10"
  DOTNET_VERSION: "8.0"
  JAVA_VERSION: "21.0"
  GO_VERSION: "1.21"

jobs:
  load-puzzle:
    name: Load Puzzle
    runs-on: ubuntu-latest
    env:
      AOC_SESSION: ${{ secrets.AOC_SESSION }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: "temurin"
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Load Puzzle
        run: |
          make prepare
          make load-puzzle year=2015 day=01
      - name: Run Tests
        run: |
          make run year=2015 day=01
