name: run

on:
  push:
    branches:
      - 2024

jobs:
  critic:
    name: Critic all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.34"

      - name: Install critic
        run: apt-get install libperl-critic-perl

      - name: Critic all
        run: make critic-all

  run:
    name: Run all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.34"
      
      - name: Run all
        run: make run-all
  
