name: run

on:
  workflow_call:
    inputs:
      year:
        type: string
        description: "Year to process"
        required: true

jobs:
  check:
    name: Check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up
        run: |
          lib/aoc/setup.sh
          lib/c/setup.sh
          lib/csharp/setup.sh
          lib/go/setup.sh
          lib/java/setup.sh
          lib/javascript/setup.sh
          lib/perl/setup.sh
          lib/python/setup.sh
          lib/aoc/post-setup.sh
          lib/aoc/version.sh

      - name: Set up dotnet - step 2
        run: dotnet tool install -g csharpier

      - name: Show versions
        run: lib/main.sh version

      - name: Check
        run: lib/main.sh check-year ${{ inputs.year }}

  run:
    name: Run
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up
        run: lib/aoc/setup.sh
      
      - name: Show versions
        run: lib/main.sh version

      - name: Run
        run: |
          echo "$AOC_SESSION_COOKIE" > session.cookie
          lib/main.sh run-year ${{ inputs.year }}
        env:
          AOC_SESSION_COOKIE: ${{ secrets.AOC_SESSION_COOKIE }}
