name: run

on:
  workflow_call:
    inputs:
      year:
        type: string
        description: "Year to process"
        required: true
        
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.34"

      - name: Install dependencies
        run: |
          sudo apt-get install bc -y
          sudo apt-get install build-essential clang clang-format clang-tidy
          sudo apt-get install libperl-critic-perl -y
          sudo apt-get install pylint isort black -y
          npm install -g eslint prettier

      - name: Check
        run: lib/main.sh check-year ${{ inputs.year }}

  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.34"
      
      - name: Install dependencies
        run: |
          sudo apt-get install bc -y
          sudo apt-get install build-essential clang clang-format clang-tidy
          sudo apt-get install libperl-critic-perl -y
          sudo apt-get install pylint isort black -y
          npm install -g eslint prettier

      - name: Run
        run: lib/main.sh run-year ${{ inputs.year }}