name: run

on:
  push

jobs:
  critic:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.34"

      - name: Install dependencies
        run: |
          sudo apt-get install bc -y
          sudo apt-get install libperl-critic-perl -y
          sudo apt-get install pylint isort black -y
          npm install -g eslint prettier

      - name: Check
        run: lib/main.sh check-all

  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.34"
      
      - name: Run
        run: lib/main.sh run-all
  
