name: run

on:
  workflow_call:
    inputs:
      year:
        type: string
        description: "Year to process"
        required: true

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Set up Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.34"

      - name: Set up Java
        run: lib/java/setup.sh

      - name: Install dependencies
        run: |
          sudo apt-get install -y bc time
          sudo apt-get install -y build-essential clang clang-format clang-tidy
          sudo apt-get install -y libperl-critic-perl
          sudo apt-get install -y pylint isort black
          npm install -g eslint prettier
          dotnet tool install -g csharpier
      
      - name: Show versions
        sun: |
          ./lib/main.sh version

      - name: Check
        run: lib/main.sh check-year ${{ inputs.year }}

  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.34"

      - name: Set up dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Set up dotnet - step 2
        run: dotnet tool install -g csharpier

      - name: Install dependencies
        run: |
          sudo apt-get install bc -y
          sudo apt-get install build-essential clang clang-format clang-tidy
          sudo apt-get install libperl-critic-perl -y
          sudo apt-get install pylint isort black -y
          npm install -g eslint prettier

      - name: Run
        run: |
          echo "$AOC_SESSION_COOKIE" > session.cookie
          lib/main.sh run-year ${{ inputs.year }}
        env:
          AOC_SESSION_COOKIE: ${{ secrets.AOC_SESSION_COOKIE }}
