name: run

on:
  push:
    branches:
      - 2024

jobs:
  critic:
    name: Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.34"

      - name: Install dependencies
        run: |
          sudo apt-get install libperl-critic-perl -y
          sudo apt-get install pylint isort black -y

      - name: Analysis
        run: make analysis-all

  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.34"
      
      - name: Run
        run: make run-all
  
