name: tests

on:
  push:
    branches:
      - chore/no-input-no-readme

env:
  PYTHON_VERSION: 3.9

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    env:
      AOC_SESSION: ${{ secrets.AOC_SESSION }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: make install

      - name: Get changed folders
        id: get_changed_folders
        run: |
          changed_folders=$(git diff --name-only --diff-filter=d $(git merge-base origin/main HEAD)..HEAD | grep -E '^([^/]+)/' | cut -d/ -f1 | sort -u)
          echo "::set-output name=changed_folders::${changed_folders}"

      - name: Process changed folders
        run: |
          for folder in ${{ steps.get_changed_folders.outputs.changed_folders }}; do
            # Perform actions for each changed folder
            # For example:
            echo "Processing folder: $folder"
            # Add your commands here to run for each folder
            # This step will be executed for every changed folder
          done
